### ISSUE TITLE
redbaron.base_nodes.NodeList.insert() raises ValueError (on in_a_shell() is False)

### ISSUE THREAD

**Issue by podhmo** [PyCQA/redbaron#121]
For Example.

``` sh
# this is OK (because in_a_shell() returns True, so __str__() is called on __repr__())
$ python myscript.py
# but this is NG. (because in_a_shel() returns False)
$ python myscript.py > output.py
```

Actually, after changing such as below.  some tests are failed.

``` diff
diff --git a/redbaron/utils.py b/redbaron/utils.py
index 451675b..91c60b7 100644
--- a/redbaron/utils.py
+++ b/redbaron/utils.py
@@ -31,6 +31,7 @@ def log(string, *args):


 def in_a_shell():
+    return False
     # the isinstance here is for building sphinx doc
     if redbaron.DEBUG or isinstance(sys.stdout, StringIO):
         return True
```

``` sh
$ py.test tests
# ... snip
======================================= 62 failed, 1346 passed in 42.57 seconds =======================================
```

**Comment by podhmo** [comment]
This is a sample script for reproducing a error.

https://gist.github.com/podhmo/d13d20a85f31127e81315eeed356e71d

```
# ValueError
$ python redbaron-error-on-insertion.py > /tmp/xxxx 
```

**Comment by podhmo** [comment]
current master is fixed?
```
$ pip freeze
-e git+git@github.com:PyCQA/redbaron.git@497a55f51a1902f67b30519c126469e60b4f569f#egg=redbaron
# ValueError is not raised.
$ python redbaron-error-on-insertion.py > /tmp/xxxx 
```

**Comment by podhmo** [comment]
Oh, I see, thanks to [this commit](https://github.com/PyCQA/redbaron/commit/725d9850), changing to ValueError is not raised, on `redbaron.DEBUG = False`

**Comment by podhmo** [comment]
(I wonder this issue's  priority is low. )
(Because reproducing error in the case that `redbaron.DEBUG = True` and `in_a_shell() returns False` only.)

**Comment by Psycojoker** [comment]
Hello,

I wanted to merge @b5y PR before doing a release (this logging thing is cause troubles to several people) but I just don't find the time nor the energy to review his PR right now, so I'm going to do a quick bugfix release and I'll take a better look at this bug ... someday :/

Thanks for reporting!

**Comment by podhmo** [comment]
OK, thanks for replying. I'm looking forward to the next release.

**Comment by Psycojoker** [comment]
Next release is there (but this was also in the previous one iirc) https://pypi.python.org/pypi/redbaron/0.6.3
