### ISSUE TITLE
Is it possible to completely disable color output from the strings?

### ISSUE THREAD

**Issue by saidctb** [PyCQA/redbaron#163]
I want to get some node's name as a string and instead of getting a normal string i get something like this  '\x1b[38;5;15mrange\x1b[39m\n'  ,is there w way to disable the ANSI escape sequences for the whole code ?

**Comment by Psycojoker** [comment]
You can do that this way:

![2018-08-04-183114_341x222_scrot](https://user-images.githubusercontent.com/41827/43678499-9941e4c2-9814-11e8-8adc-2b194ab1d80e.png)

Text version:

```
In [1]: import redbaron

In [2]: redbaron.RedBaron
Out[2]: redbaron.redbaron.RedBaron

In [3]: redbaron.RedBaron("a = 1")
Out[3]: 
0   a = 1
    

In [4]: redbaron.ipython_behavior = False

In [5]: redbaron.RedBaron("a = 1")
Out[5]: 0   a = 1
```

This should be somehow documented somewhere.

**Comment by saidctb** [comment]
thanks a lot, it works fine
