### ISSUE TITLE
.help() prints raw ANSI escapes for some constructs 

### ISSUE THREAD

**Issue by obormot** [PyCQA/redbaron#180]
RedBaron 0.9.1 from pypi
Python 3.5.6 
IPython 7.2.0

The issue is seen with empty ```{}```, ```[]``` and ```()``` in AssignmentNode. 
See the last line

```
RedBaron('foo = {}').help()
0 -----------------------------------------------------
AssignmentNode()
  # identifiers: assign, assignment, assignment_, assignmentnode
  operator=''
  target ->
    NameNode()
      # identifiers: name, name_, namenode
      value='foo'
  value ->
    [38;5;15m{[39m[38;5;15m}[39m
```

**Comment by Hanaasagi** [comment]
In `__str__`

https://github.com/PyCQA/redbaron/blob/ff14773fb67a5aec02edc50bb9114649477ef567/redbaron/base_nodes.py#L1015-L1019

`[]` will be escaped to `\x1b[38;5;15m[\x1b[39m\x1b[38;5;15m]\x1b[39m`

https://github.com/PyCQA/redbaron/blob/ff14773fb67a5aec02edc50bb9114649477ef567/redbaron/base_nodes.py#L953-L957

Which make it be escaped twice.
