### ISSUE TITLE
Cannot handle complex literals

### ISSUE THREAD

**Issue by kayhayen** [PyCQA/redbaron#40]
Hello,

this is also valid Python code: 5e5j

It's a complex literal and RedBaron needs to support it.

Yours,
Kay

**Comment by gtors** [comment]
redbaron 0.6.1 - bug not reproduced.
```
Python 3.5.2 (default, Jun 28 2016, 08:46:01)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from redbaron import RedBaron

In [2]: red = RedBaron('5e5j')

In [3]: red.fst()
Out[3]: [{'type': 'float_exponant_complex', 'value': '5e5j'}]
```

I think, issue can be closed.

**Comment by kayhayen** [comment]
I am closing due to gtors report, I will retry occasionally.

**Comment by ibizaman** [comment]
Thanks @kayhayen did you have any change reproducing this (or not)? I'm reopening this to not forget to add tests for it.

**Comment by kayhayen** [comment]
For tests. May I suggest to use something that opens a file. Parses it. Creates a file again. Then diffs. Do this with test_complex.py from there.

The issues I had reported stemmed more or less from doing this with Nuitka's own tests. I will retry later these days.

**Comment by ibizaman** [comment]
@kayhayen I added a test with specifically the example you gave that did not work. And indeed as @gtors confirmed, it works with the latest baron. I'm not at all against tests like these in general but sticked to unit testing for this one though, lazy and easy :1st_place_medal: .
