### ISSUE TITLE
Comment not parsed

### ISSUE THREAD

**Issue by Marrin** [PyCQA/redbaron#95]
Maybe this is connected to issue #67 but it's worse than just having the wrong node type, because it breaks the round trip promise:

``` python
In [27]: source = '''#!/usr/bin/env python
# coding: utf8
'''

In [28]: red = RedBaron(source)

In [29]: red
Out[29]: 
0   '#!/usr/bin/env python\n'
1   '#!/usr/bin/env python\n'


In [30]: red[0]
Out[30]: '#!/usr/bin/env python\n'

In [31]: red[1]
Out[31]: '#!/usr/bin/env python\n'

In [32]: red.dumps()
Out[32]: '#!/usr/bin/env python\n\n'
```

The second node seemingly repeats the first comment but when rendered back to source even that is gone, as is the coding comment.  Tested with Python 2.7, baron 0.6.2, and redbaron 0.6.1

**Comment by ibizaman** [comment]
Yes, comment handling is pretty brittle at the moment. Thanks for reporting!

**Comment by b5y** [comment]
Problem starts [here](https://github.com/PyCQA/baron/issues/44) from baron because [redbaron](https://github.com/PyCQA/redbaron/blob/master/redbaron/nodes.py) uses it. 
Therefore it is a baron's bug.

**Comment by gtors** [comment]
It's bug of IPython shell: [proof](https://asciinema.org/a/epx1zqn6af4oj9kh4befsuf9b)
In native python shell bug is not reproduced.

**Comment by b5y** [comment]
@gtors Interesting. I know that IPython have some bugs. One of them with StringIO I detected few months ago (it was not new version of IPython, but it does not matter). 

I have used python 2.7 and had bug with comments. Did you try with Python 2?

**Comment by gtors** [comment]
Python 2.7 shell also works fine: [asciinema](https://asciinema.org/a/d450nfzvtqp2totk97q74o0db)
p.s.: for py3 I use patched version of `baron`, so, result of calling `parse` in py2 is  a bit different.

**Comment by ibizaman** [comment]
I can unfortunately confirm it's an iPython problem:
![img-2016-12-21-230631](https://cloud.githubusercontent.com/assets/1044950/21417851/2f5a69bc-c7d2-11e6-8a5b-1a402a690b92.png)
![img-2016-12-21-230615](https://cloud.githubusercontent.com/assets/1044950/21417852/2f5b1434-c7d2-11e6-8e62-49a915d4591d.png)

@gtors do you have an idea of what the problem is?
@b5y @Marrin latest baron has (one of) the comment issue fixed, see https://github.com/PyCQA/baron/pull/88

**Comment by gtors** [comment]
@ibizaman https://github.com/ipython/ipython/issues/9919

**Comment by Marrin** [comment]
I've revisited this with current versions of IPython and the involved libraries and the problem is fixed/gone.  Given that it was a bug in IPythone anyway, I think this should be closed.
